name: Publish on tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Set up Python 3.10'
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Configure AWS Credentials for CodeArtifact
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Login to CodeArtifact
      run: |
        python -m pip install --upgrade pip
        aws codeartifact login --tool pip --repository ${{secrets.PRIVATE_REPO}} --domain ${{secrets.PRIVATE_DOMAIN}}
    - name: Configure twine for publishing
      run: |
        aws codeartifact login --tool twine --repository ${{secrets.PRIVATE_REPO}} --domain ${{secrets.PRIVATE_DOMAIN}}
    - name: Checkout
      uses: actions/checkout@v5
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install dependencies
      run: |
        make prepare-env
    - name: Lint code
      run: |
        make lint
    - name: Run tests
      run: |
        make test
    - name: Build and publish
      run: |
        make dist
        twine upload --repository codeartifact dist/*
