name: PR checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.14' ]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure AWS Credentials for CodeArtifact
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Login to CodeArtifact
      run: |
        python -m pip install --upgrade pip
        aws codeartifact login --tool pip --repository ${{secrets.PRIVATE_REPO}} --domain ${{secrets.PRIVATE_DOMAIN}}
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install dependencies
      run: |
        make prepare-env
    - name: Lint code
      run: |
        make lint
    - name: Run tests
      run: |
        make test
