name: Publish on tag

on:
  push:
    tags: 
      - '*'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Login to private pip
      run: |
        python -m pip install --upgrade pip
        aws codeartifact login --tool pip --repository ${{secrets.PRIVATE_REPO}} --domain ${{secrets.PRIVATE_DOMAIN}}
        python -m pip config --user set global.extra-index-url "https://pypi.org/simple"
    - name: Configure twine for publishing
      run: |
        aws codeartifact login --tool twine --repository ${{secrets.PRIVATE_REPO}} --domain ${{secrets.PRIVATE_DOMAIN}} 
    - name: Install dependencies
      run: |
        python -m pip install wheel twine
        python -m pip install -r requirements_dev.txt
    - name: Lint code
      run: |
        make lint
    - name: Run tests
      run: |
        make test
    - name: Build and publish
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository codeartifact dist/*
